### ISSUE TITLE
Docker-Compose fails to launch due to missing start-gui.sh

### ISSUE THREAD

**Issue by IronPiston** [juanluisbaptiste/docker-monero-wallet#2]
Trying to run the below command causes monero-wallet, monerod-data, and wallet-data to all exit:

    sudo docker-compose -p monerowallet up

![image](https://user-images.githubusercontent.com/11603684/97772122-e2e53c00-1b11-11eb-9ea7-43bd3e8f771d.png)

A start-gui.sh file seems to be missing.

**Comment by juanluisbaptiste** [comment]
Hi,

It seems the name of the wallet gui binary changed, I pushed a fix but have not tested it yet. Please test it and let me know.

**Comment by shoveln** [comment]
I'm now getting a different (and probably unrelated) error. Running the same command:
![image](https://user-images.githubusercontent.com/58153076/98329378-b7ed6300-1fbd-11eb-9177-3abf4dbcaf47.png)

**Comment by IronPiston** [comment]
I'm now getting a different (and likely unrelated) error. Running the same command: 

![image](https://user-images.githubusercontent.com/11603684/98329529-0a2e8400-1fbe-11eb-8a5c-77d7166fde39.png)

**Comment by juanluisbaptiste** [comment]
Have you defined `ENABLE_WEB_VIEW=yes` as the documentation says ?

**Comment by shoveln** [comment]
I forgot to the second time after re-cloning the repository. All works now, thanks!

**Comment by IronPiston** [comment]
I forgot to the second time after re-cloning the repository. All works now, thanks!

**Comment by juanluisbaptiste** [comment]
btw, I just updated the wallet version if you want to test it.
